@startuml

title Dataset Pipeline Diagram

node "NetKeiba" as NetKeiba

Rectangle "Averages" as Averages {
    Rectangle "AverageFrames" as AverageFrames {
        Rectangle "{COURSE_LIST}" as couseAF {
            node "{year}_AverageFrames" as yearAF
            node "{year}_AverageFrames_top3" as yearAF_top3
            node "total_AverageFrames" as totalAF
            node "total_AverageFrames_top3" as totalAF_top3
        }
    }

    Rectangle "AveragePops" as AveragePops {
        Rectangle "{COURSE_LIST}" as couseAP {
            node "{year}_AveragePops" as yearAP
            node "{year}_AveragePops_top3" as yearAP_top3
            node "total_AveragePops" as totalAP
            node "total_AveragePops_top3" as totalAP_top3
        }
    }
    Rectangle "AverageTimes" as AverageTimes {
        Rectangle "{COURSE_LIST}" as couseAT {
            node "{year}_avg_time" as yearAT
            node "{year}_winner_time" as yearAT_winner
            node "total_avg_time" as totalAT
            node "total_winner_time" as totalAT_winner
        }
    }
    Rectangle "AverageWegiths" as AverageWeights {
        Rectangle "{COURSE_LIST}" as couseAW {
            node "{year}_winner_weight" as yearAW
            node "total_winner_weight" as totalAW
        }
    }
}
Rectangle "HorsePeds" as HorsePeds {
    node "hosrse_id" as horseIDpeds
}
Rectangle "PastPerformances" as PastPerformances {
    node "horse_id" as horseIDpast
}
Rectangle "PedsResults" as PedsResults {
    Rectangle "{COURSE_LIST}" as coursePR {
        Rectangle "{year}" as yearPR {
            node "{type}_len_all" as YearAllPR
            node "{type}_len_{class}" as YearClassPR
        }
        Rectangle "total" as totalPR {
            node "{type}_len_all" as TotalAllPR
            node "{type}_len_{class}" as TotalClassPR
        }
        node "{year}_peds" as yearPeds
        node "{year}_peds_data" as yearPedsData
    }
}

Rectangle "RaceCards" as RaceCards {
    Rectangle "{datestr}" as dateRC {
        node "{race_id}" as raceIDRC
    }
}
Rectangle "RaceInfo" as RaceInfo {
    Rectangle "{COURSE_LIST}" as yearRaceInfo {
        node "{race_id}" as raceIDRI
    }
}

Rectangle "RaceResults" as RaceResults {
    Rectangle "{COURSE_LIST}" as RaseResultsCourse {
        Rectangle "{year}" as RaseResultsYearFolder {
            node "{race_id}" as RaseResultsRaceID
        } 
        node "year_race_results" as RaseResultsYear
    }
}
Rectangle "RaceReturns" as RaceReturns {
    Rectangle "{COURSE_LIST}" as RaseReturnsCourse {
        Rectangle "{year}" as RaseReturnsYearFolder {
            node "{race_id}" as RaseReturnsRaceID
        } 
        node "year_race_results" as RaseRetunrsYear
    }
}
node "horse_id_map" as HorseIDMap

' Rectangle "PredictionModels" as PredictionModels {
'     Rectangle "LightGBM" as LightGBM {
'         Rectangle "Database" as LGBM_DB {
'             Rectangle "{COURSE_LIST}" as courseLGBM {
'                 node "{year}_{course}{len}_ai_dataset_flag" as yearLGBM
'                 node "{year}_{course}{len}_ai_dataset_for_rank" as yearLGBM_rank
'             }
'         }
'         Rectangle "Models" as LGBM_Models {
'             Rectangle "{COURSE_LIST}" as courseLGBM_Models {
'                 node "{course}{len}_lambdarank_model" as courseLGBMModel
'             }
'         }
'     }
' }


' RaceResults
NetKeiba --> RaseResultsRaceID
NetKeiba --> RaseResultsYear

' PedsResults
NetKeiba --> horseIDpeds
yearPedsData --> YearAllPR
yearPedsData --> YearClassPR
yearPedsData --> TotalAllPR
yearPedsData --> TotalClassPR
horseIDpeds --> yearPeds
RaseResultsYear --> yearPeds
RaseResultsYear --> yearPedsData
yearPeds --> yearPedsData

' Averages
RaseResultsYear --> Averages
' RaseResultsYear --> AveragePops
' RaseResultsYear --> AverageFrames
' RaseResultsYear --> AverageWeights

' PastPerformances
RaseResultsYear --> horseIDpast

' RaceReturns
NetKeiba --> RaseReturnsRaceID

' RaceCards
NetKeiba --> raceIDRC
horseIDpast --> raceIDRC
horseIDpeds --> raceIDRC

' RaceInfo
NetKeiba --> raceIDRI

' HorseIDMap
RaseResultsYear --> HorseIDMap

@enduml